---
title: "Analyze counts"
author: "`r Sys.info()[['user']]`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  github_document:
    toc: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

## Load libraries and define analysis-specific variables
```{r}
library(tidyverse)
library(rasilabRtemplates)

initiationmutation_order <- seq(1,9)
names(initiationmutation_order) <- toupper(c('ctg', 'ctgc', 'ccgc', 
                              'acgc', 'ccga', 'ccac', 'ccaa', 'caaa', 'aaaa'))
```

## Read annotations
```{r}
sampleannotations <- read_tsv("../../../data/htseq/initiation_pgk1_no_insert/sampleannotations.tsv") %>% 
  print()
```

## Read in data
```{r}
data <- "../../../tables/htseq/initiation_pgk1_no_insert/" %>% 
  list.files(pattern = ".tsv", full.names = T) %>% 
  enframe("sno", "file") %>% 
  mutate(barcode = str_extract(file, "(?<=/)[ACTG]{6}")) %>% 
  mutate(data = map(file, read_tsv)) %>% 
  left_join(sampleannotations, by = "barcode") %>% 
  filter(is.na(row) & is.na(column)) %>%
  select(-sno, -file, -barcode) %>% 
  unnest() %>% 
  print()
```

## Plot of median-normalized cDNA and gDNA counts for concordance between varying PCR cycles

```{r flag_mrna_stability_vs_initiation_rate, fig.width=1.5, fig.height=1.5}
flag_data <- data %>% 
  filter(gene == "flag") %>% 
  # get the initiation mutation as either CTG at start or the -4 to -1 preceding ATG
  mutate(init_mutation = str_extract(init, '(?<=CAAA)CTG|[ACTG]{4}(?=ATG)')) %>% 
  # get only initiation mutations that we cloned 
  filter(init_mutation %in% names(initiationmutation_order)) %>% 
  # arrange init_mutation in correct_order
  mutate(init_mutation = forcats::fct_reorder(
    init_mutation, initiationmutation_order[init_mutation]))

plot_data <- flag_data %>% 
  group_by(init_mutation, type) %>% 
  summarize(count = sum(count)) %>% 
  ungroup() %>% 
  # spread cdna and gdna counts to adjacent columns
  spread(type, count) %>% 
  # calculate log2 fold change cdna / gdna
  mutate(lfc = log2(cdna)-log2(gdna)) %>% 
  # median normalize lfc 
  mutate(lfc = lfc - median(lfc)) 

plot_data %>% 
  ggplot(aes(x = init_mutation, y = lfc, group = NA)) +
  geom_line(color = "dimgrey") +
  geom_point(shape = 21, fill = "dimgrey") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6)) +
  labs(x = "Kozak (-4 to -1)", y = "mRNA level (log2, a.u.)",
       title = "PGK1-YFP, no insert") +
  NULL

ggsave("../../../figures/mrna_stability_vs_initiation_rate_pgk1_no_insert.pdf")
```