---
title: "Analyze simulation results"
author: "`r Sys.info()[['user']]`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  github_document:
    toc: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

## Load libraries
```{r}
library(tidyverse)
library(rasilabRtemplates)
# disable scientific notation
options(scipen=999)
```

## Read protein count data
```{r}
psr_data <- read_tsv("tables/psr_stats.tsv") %>% 
  print()
```

## Read simulation parameters
```{r}
annotations  <- read_tsv('sim.params.tsv', 
                         col_types = cols(x_stall = col_character(),
                                          k_elong_stall = col_character())) %>%
  mutate(preterm_intact_model = if_else(preterm_intact_rate == 0, 
                                        "trafficjam", 
                                        preterm_intact_model)) %>% 
  rename(sim_id = X1) %>%
  mutate(k_elong_stall = str_split(k_elong_stall, ",")) %>%
  mutate(k_elong_stall = map(k_elong_stall, as.numeric)) %>%
  mutate(k_elong_stall = map(k_elong_stall, function(x) unique(x))) %>%
  unnest() %>%
  mutate(x_stall = stringr::str_split(x_stall, ',')) %>%
  mutate(k_stall = as.factor(k_elong_stall / as.numeric(n_stall))) %>%
  filter(n_stall <= 6) %>% 
  mutate(n_stall = factor(n_stall)) %>%
  select(sim_id, k_init, k_elong_stall, k_stall, x_stall, n_stall,
         preterm_intact_model, preterm_intact_rate) %>%
  print()
```

## Combine all data into a single table
```{r}
data <- annotations %>% 
  left_join(psr_data, by = "sim_id") %>% 
  print()
```

## How does PSR vary as a function of initiation rate and number of stall sites with low stall elongation rate and medium preterm_intact_rate?


```{r psr_no_quality_control, fig.width=2.2, fig.height=1.5}
plot_data <- data %>% 
  filter(preterm_intact_rate == 1 & k_stall == 0.1)

plot_data %>% 
  ggplot(aes(x = k_init, y = psr, color = n_stall, group = n_stall)) +
  geom_point(size = 1) + geom_line(size = 0.5) +
  scale_x_continuous(trans = "log2",
                     breaks = scales::trans_breaks("log2", function(x) 2^x),
                     labels = scales::trans_format("log2", scales::math_format(2^.x)),
                     limits = c(2^-8, 2^0)) +
  scale_y_continuous(limits = c(0, NA)) +
  guides(color = guide_legend(
                 keywidth=0.1,
                 keyheight=0.15,
                 default.unit="inch")
      )  + 
  viridis::scale_color_viridis(discrete = T, end = 0.9) +
  # scale_shape_manual(values = c(0, 1, 2, 5, 6)) +                                                  
  labs(x = "initiation rate (s-1)", y = "protein synthesis rate (s-1)",
       color = "number\nof stalls", shape = "") +
  theme(legend.key.height = unit(0.2, "in"))                     
                         
ggsave('figures/psr_csat_effect_of_num_stalls.pdf') 
```

# Source data for Fig. 3C

```{r}
plot_data %>% 
  select(n_stall, k_init, psr) %>% 
  knitr::kable()
```

