"""Workflow for running simulations in this folder

  :Author: Arvind Rasi Subramaniam
  :Date: 18 Dec 2018
"""

# This generates the sim.params.tsv below
include: "choose_simulation_parameters.py"

import pandas as pd
input_params = pd.read_table("sim.params.tsv", index_col=0)


# These rules are run locally
localrules: all, analyze_data


rule all:
  """List of all files we want at the end"""
  input: 
    "analyze_results.md"


rule run_simulation:
  """Run simulation for each parameter combination"""
  input:
    "../../tasep.py",
    "choose_simulation_parameters.py"
  output:
    "output/tasep_{n}_.rxns.tsv",
    "output/tasep_{n}_.params.tsv.gz",
    "output/tasep_{n}_connect.rxns.tsv",
    "output/tasep_{n}_connect.params.tsv.gz"
  shell:
    "python run_simulation.py {wildcards.n}"


rule analyze_data:
  """Analyze results and make figures"""
  input: 
    [f"output/tasep_{n}_.rxns.tsv" for n in range(len(input_params))],
    [f"output/tasep_{n}_.params.tsv.gz" for n in range(len(input_params))],
    [f"output/tasep_{n}_connect.rxns.tsv" for n in range(len(input_params))],
    [f"output/tasep_{n}_connect.params.tsv.gz" for n in range(len(input_params))]
  output:
    "analyze_results.md"
  script:
    "analyze_results.Rmd"
