---
title: "Fluorescence of PGK1 reporters with 5xCGG / 5xAGA inserts and varying Kozak in ASC1 KO background"
author: "`r Sys.info()[['user']]`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  github_document:
    toc: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Import libraries and analysis specific parameters

```{r}
# loads lab default ggplot2 theme and provides color-blind friendly palette
library(rasilabRtemplates)
# standard analysis and plotting functions, includes dplyr, ggplot2 
library(tidyverse)
# standard error
library(plotrix)

# intiiation sites are arranged in this order
initiationmutation_order <- seq(1,8)
names(initiationmutation_order) <- toupper(c( 'ctgc', 'ccgc', 
                              'acgc', 'ccga', 'ccac', 'ccaa', 'caaa', 'aaaa'))

# bad wells that had zero or abnormal signals. These are excluded from analysis.
bad_wells <- list(
    list('strain' = 'schp539' , 'replicate' = 1),
    list('strain' = 'schp550' , 'replicate' = 3),
    list('strain' = 'schp551' , 'replicate' = 2),
    list('strain' = 'schp540' , 'replicate' = 1),
    list('strain' = 'schp540' , 'replicate' = 3),
    list('strain' = 'schp540' , 'replicate' = 4)
) %>% 
  bind_rows()

# this folder contains the data and annotations
fcs_file_folder <- "../../data/flow/5xcgg_asc1ko/"
```

```{r, eval = T, include = FALSE}
# Combine raw .fcs files into a single dataframe for manuscript
# This chunk is for preprocessing and is not evaluated (`eval = FALSE`).

raw_data <- fcs_file_folder %>% 
  # get all fcs files
  list.files(full.names = T, pattern = '.fcs$') %>% 
  enframe("sno", "filename") %>% 
  # get data from each file
  mutate(data = map(filename, . %>% 
                      flowCore::read.FCS(transformation = F, alter.names = T) %>% 
                      flowCore::exprs() %>% 
                      as_tibble())) %>% 
  # extract plate and well
  mutate(plate = as.integer(str_extract(filename, "(?<=Specimen_)[:digit:]{3}"))) %>%
  mutate(well = str_extract(filename, "(?<=Specimen_[:digit:]{3}_)[:alnum:]+")) %>%
  # get rid of unwanted columns
  select(-sno, -filename) %>% 
  unnest() %>% 
  # round nicely for storing
  mutate_at(vars(matches("Time")), funs(round(., 3))) %>% 
  mutate_at(vars(-matches("Time|well")), funs(as.integer)) %>% 
  print()
```

```{r, eval = T, include = FALSE}
# Clean annotations file for manuscript
# This chunk is for preprocessing and is not evaluated (`eval = FALSE`).

annotations <- paste0(fcs_file_folder, '/sampleannotations.tsv') %>% 
                        read_tsv(col_types = list('plate' = col_integer())) %>% 
  # rename col
  rename(gene = genes) %>%
  # replace all 'na' ny NA
  mutate_all(funs(ifelse(. == 'na', NA, .))) %>%
  # extract number of stall sites
  mutate(numberofstallsites =
         ifelse(is.na(stallsites),
                0,
                str_count(stallsites, ',') + 1)) %>%
  # the default initiation mutation is CAAA
  mutate(initiationmutation = if_else(is.na(initiationmutation), "CAAA",
                                      initiationmutation)) %>%
  mutate(initiationmutation = toupper(initiationmutation)) %>%
  # arrange initiationmutation in this order
  mutate(initiationmutation = fct_reorder(
      initiationmutation,
      initiationmutation_order[initiationmutation])) %>%
  mutate(well = str_extract(file, "(?<=Specimen_[:digit:]{3}_)[:alnum:]+")) %>%
  mutate(strain = str_replace(strain, "schp0", "schp")) %>%
  # these are genes of interest or the standard control strains
  filter(gene == "pgk1" & numberofcodonrepeats == 5 | strain %in% c("schp19", "schp20", "schp15", "by4741")) %>% 
  mutate(knockoutgenes = if_else(is.na(knockoutgenes), "WT", paste0("Δ", toupper(knockoutgenes)))) %>% 
  rename(knockout = knockoutgenes) %>%
  select(plate, well, strain, replicate, initiationmutation, codonmutation, gene, knockout) %>% 
  write_tsv(paste0(fcs_file_folder, '/annotations.tsv')) %>% 
  print()
```

```{r, eval = T, include = FALSE}
# Keep only the data that we need for manuscript
# This chunk is for preprocessing and is not evaluated (`eval = FALSE`).
raw_data %>% 
  right_join(select(annotations, plate, well)) %>% 
  filter(!is.na(FITC.A) & !is.na(PE.Texas.Red.A)) %>%
  write_tsv(paste0(fcs_file_folder, '/data.tsv'))
```

# Read data

```{r}
flowdata  <- read_tsv(paste0(fcs_file_folder, '/data.tsv')) %>% 
  print()
```

# Read annotations

```{r}
annotations  <- read_tsv(paste0(fcs_file_folder, '/annotations.tsv')) %>% 
  print()
```

# Rename and calculate average values of fluorescence channels in each well

```{r}
by_file <- flowdata  %>% 
  # group by each plate and well
  group_by(plate, well) %>% 
  select(FITC.A, PE.Texas.Red.A) %>% 
  # calculate mean
  summarise_all(mean) %>% 
  # rename
  rename('yfp' = FITC.A, 'rfp' = PE.Texas.Red.A) %>% 
  # join annotations
  left_join(annotations, by = c('plate', 'well')) %>% 
  print()
```

# Calculate mean and standard error over replicates

```{r}
avg_data  <- by_file %>% 
  anti_join(bad_wells) %>%
  # strain is used to get replicates
  group_by(strain) %>% 
  # calculate mean and std.err
  mutate(mean_yfp = mean(yfp), 
         mean_rfp = mean(rfp)) %>% 
  ungroup() %>% 
  mutate(yfp = yfp - mean_yfp[strain == "schp15" & replicate == 1], 
         rfp = rfp - mean_rfp[strain == "by4741" & replicate == 1]) %>% 
  mutate(yfp_rfp_ratio = yfp / rfp) %>% 
  # calculate mean and standard error
  group_by(strain) %>% 
  mutate(mean_yfp = mean(yfp), 
         mean_rfp = mean(rfp), 
         mean_ratio = mean(yfp_rfp_ratio), 
         se_yfp = std.error(yfp), 
         se_rfp = std.error(rfp),
         se_ratio = std.error(yfp_rfp_ratio),
         n = n()) %>% 
  slice(1) %>% 
  ungroup() %>% 
  print()

normalization <- avg_data %>% 
  filter(strain == "schp19")
```


# Plot mean YFP / RFP ratio as a function of initiation codon

```{r, fig.width=2.6, fig.height=3}
plot_data <- avg_data %>% 
  mutate(mean_ratio = mean_ratio / normalization[[1, "mean_ratio"]]) %>%
  mutate(se_ratio = se_ratio / normalization[[1, "mean_ratio"]]) %>%
  filter(gene == "pgk1") %>% 
  mutate(codonmutation = forcats::fct_rev(paste0("5×", toupper(codonmutation)))) %>%
  mutate(knockout = forcats::fct_relevel(knockout, "ΔASC1")) %>% 
  filter(initiationmutation != "CTG") %>%
  # arrange initiationmutation in this order
  mutate(initiationmutation = fct_reorder(
      initiationmutation,
      initiationmutation_order[initiationmutation])) %>%
  print()

plot_data %>%
  ggplot(aes(x = initiationmutation, y = mean_ratio,
             ymin = mean_ratio - se_ratio, ymax = mean_ratio + se_ratio,
             group = codonmutation, color = codonmutation, shape = codonmutation)) +
  geom_errorbar(width = 0.5, color = "black") +
  geom_point(size = 2, height = 0, width = 0.1) +
  geom_line(size = 0.5) +
  facet_wrap(codonmutation ~ knockout, ncol = 1, scales = "free") +
  scale_color_manual(values = cbPalette[c(2,1)]) +
  scale_shape_manual(values = c(17,16)) +
  labs(y = 'fluorescence (a.u.)',
       x = '-4 to -1 nt from ATG', color = "", shape = "") +
  theme(legend.title = element_text(size = 8),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 6)) +
  scale_y_continuous(breaks = scales::pretty_breaks(n=4))

ggsave('figures/5xcgg_asc1ko.pdf')

plot_data %>% 
  arrange(knockout, codonmutation, initiationmutation) %>% 
  select(knockout, codonmutation, initiationmutation, mean_ratio, se_ratio, n) %>% 
  mutate_if(is.numeric, funs(round(., 3))) %>% 
  knitr::kable()
```
