---
title: "Analyze simulation results"
author: "`r Sys.info()[['user']]`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  github_document:
    toc: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

## Load libraries
```{r}
library(tidyverse)
library(rasilabRtemplates)
# disable scientific notation
options(scipen=999)

cleave_model_names <- c(
  "hit5" = "CSEC",
  "simple" = "SEC",
  "trafficjam" = "TJ"
)
```

# Read protein count data

```{r}
psr_data <- read_tsv("tables/psr_stats.tsv") %>% 
  print()
```

# Read simulation parameters

```{r}
annotations <- list.files("output/", pattern = "params.tsv.gz$", full.names = T) %>% 
  enframe("sno", "file") %>% 
  mutate(sim_id = str_extract(file, "(?<=tasep_)[[:digit:]]+")) %>% 
  mutate(data = map(file, read_tsv)) %>% 
  select(-file, -sno) %>% 
  unnest() %>% 
  type_convert() %>% 
  # retain only parameters that are varied, the others are for checking
  group_by(parameter) %>% 
  mutate(vary = if_else(length(unique(value)) > 1, T, F)) %>% 
  ungroup() %>% 
  filter(vary == T) %>% 
  select(-vary) %>% 
  spread(parameter, value) %>% 
  print()
```

# Combine all data into a single table

```{r}
data <- annotations %>% 
  left_join(psr_data, by = "sim_id") %>% 
  filter(n_stall <= 6) %>%
  mutate(n_stall = as.factor(n_stall)) %>% 
  print()
```

# PSR as a function of number of stalls for supplementary figure

```{r, fig.width=2.2, fig.height=1.5}
plot_data <- data

plot_data %>%
  ggplot(aes(x = k_init, y = psr, color = n_stall, group = n_stall)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(trans = "log2",
                     labels = scales::trans_format("log2", scales::math_format(2^.x)),
                     breaks = 2^(seq(-8,0,2))) +
  scale_y_continuous(limits = c(0, 0.06)) +
  viridis::scale_color_viridis(discrete = T, end = 0.9) +
  labs(x = "initiation rate (s-1)", y = "protein synthesis rate (s-1)",
       color = "number\nof stalls", shape = "") +
  theme(legend.key.height = unit(0.2, "in")) +
  guides(color = guide_legend(
                 keywidth=0.1,
                 keyheight=0.15,
                 default.unit="inch")
      )

ggsave("figures/psr_vs_initiation_rate_vary_n_stalls.pdf")
```

