---
title: "Analyze simulation results"
author: "`r Sys.info()[['user']]`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  github_document:
    toc: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

## Load libraries
```{r}
library(tidyverse)
library(rasilabRtemplates)
# disable scientific notation
options(scipen=999)

cleave_model_names <- c(
  "hit5" = "CSEC",
  "simple" = "SEC",
  "trafficjam" = "TJ"
)
```

# Read protein count data

```{r}
psr_data <- read_tsv("tables/psr_stats.tsv") %>% 
  print()
```

# Read mRNA lifetime data

```{r}
lifetime_data <- read_tsv("tables/mrna_lifetime_stats.tsv") %>% 
  mutate(se_lifetime = sd_lifetime / sqrt(n_mrna)) %>% 
  print()
```

# Read simulation parameters

```{r}
sim_params <- read_tsv("sim.params.tsv") %>% 
  rename(sim_id = X1) %>% 
  mutate(k_elong_stall = str_split(k_elong_stall, ",")) %>%
  mutate(k_elong_stall = map(k_elong_stall, as.numeric)) %>%
  mutate(k_elong_stall = map(k_elong_stall, function(x) unique(x))) %>%
  unnest() %>%
  mutate(x_stall = stringr::str_split(x_stall, ',')) %>%
  mutate(k_stall = k_elong_stall / as.numeric(n_stall)) %>%
  select(sim_id, cleave_rate, cleave_model, k_stall) %>% 
  print()

annotations <- list.files("output/", pattern = "params.tsv.gz$", full.names = T) %>% 
  enframe("sno", "file") %>% 
  mutate(sim_id = str_extract(file, "(?<=tasep_)[[:digit:]]+")) %>% 
  mutate(data = map(file, read_tsv)) %>% 
  select(-file, -sno) %>% 
  unnest() %>% 
  type_convert() %>%
  # retain only parameters that are varied, the others are for checking
  group_by(parameter) %>%
  mutate(vary = if_else(length(unique(value)) > 1, T, F)) %>%
  ungroup() %>%
  filter(vary == T) %>%
  select(-vary) %>%
  spread(parameter, value) %>%
  left_join(sim_params, by = "sim_id") %>% 
  print()
```

# Combine all data into a single table

```{r}
data <- annotations %>% 
  left_join(psr_data, by = "sim_id") %>% 
  left_join(lifetime_data, by = "sim_id") %>% 
  print()
```

# mRNA lifetime as a function of endonucleolytic cleavage rate

```{r, fig.width=3, fig.height=2.2}
plot_data <- data %>% 
  mutate(model = cleave_model_names[cleave_model]) %>% 
  mutate(model_stall = paste0(model, "_", k_stall))

plot_data %>%
  ggplot(aes(x = cleave_rate, y = mean_lifetime, color = model, shape = model_stall)) +
  facet_wrap(~model, ncol = 2, scales = "free") +
  scale_y_continuous(limits = c(0, 2200)) +
  geom_line() +
  geom_point(size = 1.5) +
  scale_x_continuous(trans = "log2",
                     labels = scales::trans_format("log2", scales::math_format(2^.x)),
                     breaks = scales::trans_breaks("log2", function(x) 2^x, n = 5)) +
  scale_color_manual(values = cbPalette[c(3,2)]) +
  scale_shape_manual(values = c(19, 1, 17, 2)) +
  labs(x = "endonucleolytic cleavage rate (s-1)", 
       y = "mean mRNA lifetime (s)", color = "", shape = "") +
  theme(legend.position = "top")

ggsave("figures/mrna_lifetime_vs_cleavage_rate.pdf", width = 3, height = 2.2)
```